### PR TITLE
adding monitor-connection.coffee for annoying disconnects

### PR DESCRIPTION
**Pull request by craigske**

### CODE REVIEW

**Comment by craigske** [comment]
@lancehudson ping

**Comment by willasaywhat** [comment]
Merged; if we need a deploy I'll bug Lance. Be advised the disconnects may have to do with Heroku, too.

**Comment by lancehudson** [comment]
Deploy failed, some cert error, retrying.

**Comment by lancehudson** [comment]
FYI currently 
Downloading and installing node 0.10.25...
       Using default npm version: 1.3.24

**Comment by lancehudson** [comment]
Same, error, my suggestion is to upgrade the Heroku build pack. I can try to do this later.

**Comment by lancehudson** [comment]
We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - This version of npm (1.3.24) has several known issues - consider upgrading to the latest release (5.8.0)
       https://devcenter.heroku.com/articles/nodejs-support#specifying-an-npm-version

**Comment by craigske** [comment]
yep, agree. I should probably figure out a dev bot env or something. It's weird chucking a PR in with no CI or testing.

**Comment by lancehudson** [comment]
thank you for volunteering to setup ci ;)

**Comment by lancehudson** [comment]
send me your email, ill add you to heroku

**Pull request merged**
